api/.babelrc, api/README.md, api/package.json, api/serverless.yml, api/src/domain/common/formats.js, api/src/domain/configurations/add.js, api/src/domain/configurations/get.js, api/src/domain/configurations/history.js, api/src/domain/configurations/update.js, api/src/domain/configurations/version.js, api/src/domain/environments/add.js, api/src/domain/environments/get.js, api/src/domain/environments/remove.js, api/src/domain/environments/rename.js, api/src/domain/projects/add.js, api/src/domain/projects/remove.js, api/src/domain/projects/rename.js, api/src/handlers/configurations.js, api/src/handlers/environments.js, api/src/handlers/projects.js, api/src/handlers/utils/λ.js, api/src/queries/configurations.js, api/src/queries/db.js, api/src/queries/entries.js, api/src/queries/environments.js, api/src/queries/projects.js, api/src/queries/tags.js, api/src/queries/versions.js
=> [RFR] Fix queries & architecture

api/src/domain/configurations/add.js, api/src/domain/configurations/version.js
=> [RFR] Do not change the tag if we don't want to

api/serverless.yml, api/src/domain/configurations/add.js, api/src/domain/configurations/get.js, api/src/domain/configurations/history.js, api/src/domain/configurations/tag.js, api/src/handlers/configurations.js, api/src/queries/configurations.js, api/src/queries/versions.js, cli/src/commands/get.js, cli/src/commands/ls.js, cli/src/domain/config.js
=> [RFR] Unwanted tag changes + all history

.travis.yml, Makefile, cli/.eslintrc, cli/Makefile, cli/package.json, cli/src/crypto.spec.js
=> [RFR] Init tests

cli/src/format/index.js
=> [RFR] Secure envvars format

api/src/queries/configurations.js, api/src/queries/environments.js, api/src/queries/projects.js
=> [RFR] Filter all queries by live state

api/src/domain/configurations/version.js, api/src/domain/environments/add.js, cli/.eslintrc, cli/src/commands/env.js, cli/src/domain/environment.js
=> [RFR] Add a new environment

Makefile, api/makefile, cli/.npmignore, cli/package.json, cli/src/commands/get.js, cli/src/domain/constants.js, package.json
=> [RFR] Prepare NPM release

README.md, api/package.json, api/serverless.yml, api/src/domain/configurations/version.js, api/src/domain/tags/add.js, api/src/domain/tags/move.js, api/src/domain/tags/remove.js, api/src/domain/tags/validator.js, api/src/handlers/tags.js, api/src/handlers/utils/λ.js, api/src/queries/tags.js, api/src/queries/versions.js, api/webpack.config.babel.js, cli/src/client.js, cli/src/commands/add.js, cli/src/commands/env.js, cli/src/commands/tag.js, cli/src/domain/tag.js, cli/src/index.js
=> [RFR] Add tag move add edit

cli/package.json, cli/src/domain/config.js, cli/src/format/toFlat.js
=> [RFR] Handle null values

cli/package.json, cli/src/domain/config.js
=> [RFR] Fix nullable value to include only `null` and `undefined`

cli/src/commands/init.js
=> [RFR] Update init command wording

README.md, cli/src/commands/init.js, cli/src/domain/constants.js, cli/src/domain/project.js
=> [RFR] Improve init command syntax, remove interactive mode unless necessary

Makefile, admin/Makefile, admin/package.json, admin/src/App.js, admin/src/Login.js, admin/src/provideAppState.js, admin/src/provideAppState.test.js, admin/src/provideLoginState.js, admin/src/provideLoginState.test.js
=> [RFR]Freactal

.gitignore, admin/package.json, admin/src/App.js, admin/src/App.test.js, admin/src/Environment.js, admin/src/Login.js, admin/src/fetch/fetchConfig.js, admin/src/fetch/handleFetchResponse.js, admin/src/fetch/handleFetchResponse.test.js, admin/src/fetch/state.js, admin/src/index.js, admin/src/provideAppState.js, admin/src/provideConfigState.js, admin/src/provideConfigState.test.js, admin/src/provideLoginState.js, admin/src/provideLoginState.test.js, admin/src/utils/wrapWithErrorHandling.js, admin/src/utils/wrapWithErrorHandling.test.js, admin/src/utils/wrapWithLoading.js, admin/src/utils/wrapWithLoading.test.js, admin/yarn.lock, package.json
Take 2 as we messed up with git
=> [RFR] Admin - Load config

admin/package.json, admin/src/App.js, admin/src/Environment.js, admin/src/Login.js, admin/src/index.js, admin/src/provideAppState.js, admin/src/provideAppState.test.js, admin/src/provideConfigState.js, admin/src/provideConfigState.test.js, admin/src/provideLoginState.js, admin/src/provideLoginState.test.js, admin/yarn.lock
=> [RFR] Admin - refactoring

admin/package.json, admin/src/Environment.js, admin/src/components/EnvironmentItem.js, admin/yarn.lock
=> [RFR] Switch to hidden values by default

admin/src/Environment.js, admin/src/components/Sidebar.js, admin/src/components/SidebarItem.js
=> [RFR] Admin - styles

admin/bin/comfy-admin.js, admin/config/webpack.config.cmd.js, admin/config/webpack.config.dev.js, admin/config/webpack.config.prod.js, admin/src/App.js, admin/src/cmdConfig.js, admin/src/index.js, admin/src/provideLoginState.js, admin/src/provideLoginState.test.js
=> [RFR] Faster admin

admin/package.json, admin/src/Environment.js, admin/src/components/ConfirmDialog.js, admin/src/components/EnvironmentItem.js, admin/src/components/RemoveConfigKeyDialog.js, admin/src/provideConfigState.js, admin/src/provideConfigState.test.js, admin/yarn.lock, api/src/domain/configurations/get.js
=> [RFR] Admin - Remove an config entry

admin/package.json, admin/src/Environment.js, admin/src/provideConfigState.js, admin/src/provideConfigState.test.js
=> [RFR] Search as you type

admin/src/Environment.js, admin/src/provideConfigState.js, config-dev.json, config-prod.json
=> [RFR] Admin - add a new config key

admin/src/App.js, admin/src/Environment.js, admin/src/components/EnvironmentItem.js, admin/src/components/Sidebar.js
=> [RFR] Use table for config keys

README.md, cli/src/commands/init.js, cli/src/commands/setall.js, cli/src/index.js
=> [RFR] Rename add command to setall, simplify syntax

.gitignore, .travis.yml, Makefile, cli/package.json, test/.eslintrc, test/Makefile, test/cli.js, test/package.json, test/pm2_configuration.json, test/setup.js, test/specs/basicUsage.js, test/specs/formats.js, test/specs/init.js
Introduce E2E test which run the API and use it through the command.
The application is tested with real input and ouput sent to the client.
Since we only test client output, we don't need to load fixtures or reset it each time.
Instead, all the commands are run in a specific folder (`test/.env`) which is deleted between all the tests.
=> [RFR] Minimal test suite

test/specs/scenarios.js
=> [RFR] Test child entry deletion

cli/src/crypto/index.js, cli/src/crypto/serialization.js, cli/src/crypto/serialization.spec.js, cli/src/domain/config.js, test/specs/scenarios.js
=> [RFR] Serialize configuration entries

cli/src/commands/setall.js, cli/src/ui/console.js, test/.eslintrc, test/specs/commands.js
=> [RFR] setall: Fix absolute config path

api/src/domain/projects/remove.js, cli/package-lock.json, cli/package.json, cli/src/commands/get.js, cli/src/commands/help.js, cli/src/commands/project.js, cli/src/domain/project.js, cli/src/index.js, cli/src/ui/console.js, test/cli.js, test/specs/commands.js
=> [RFR]  Add a command to delete a project

.travis.yml, cli/src/commands/help.js, cli/src/commands/set.js, cli/src/crypto/index.js, cli/src/domain/config.js, cli/src/index.js, test/specs/commands.js
=> Set command

api/src/domain/configurations/history.js, api/src/queries/versions.js, cli/src/commands/log.js, test/specs/basicUsage.js
=> Display log time

api/serverless.yml, api/src/domain/configurations/get.js, api/src/handlers/configurations.js, cli/src/commands/get.js, cli/src/domain/config.js, test/specs/commands.js
Fixes #18 
```
comfy get staging --hash=5eb9f3ea5cf01384333115007cf7606f --yml > config/staging.yaml
```
=> [RFR] Get by hash

cli/src/domain/project.js, cli/src/index.js
=> Display beta deprecation warning

.travis.yml, api/src/domain/configurations/add.js, api/src/domain/configurations/get.js, api/src/domain/configurations/update.js, api/src/domain/configurations/version.js, api/src/domain/environments/add.js, cli/package-lock.json, cli/src/commands/get.js, cli/src/commands/set.js, cli/src/commands/setall.js, cli/src/commands/tag.js, test/specs/basicUsage.js, test/specs/commands.js, test/specs/scenarios.js
=> Change default tags to 'latest'

api/makefile, api/serverless.yml, api/src/handlers/configurations.js, api/src/index.js
Protip: Review this PR with `w=1` to remove whitespace diff.
https://github.com/marmelab/comfygure/pull/151/files?w=1
=> Fix url variable name

.travis.yml, cli/package-lock.json, cli/src/commands/diff.js, cli/src/commands/get.js, cli/src/commands/help.js, cli/src/domain/config.js, cli/src/index.js, test/specs/commands.js
=> New command: comfy diff <env> <hash|tag> [<hash|tag>]

cli/.eslintrc, cli/package-lock.json, cli/package.json, cli/src/client.js, cli/src/commands/admin.js, cli/src/commands/env.js, cli/src/commands/get.js, cli/src/commands/help.js, cli/src/commands/init.js, cli/src/commands/project.js, cli/src/commands/set.js, cli/src/commands/setall.js, cli/src/commands/tag.js, cli/src/commands/version.js, cli/src/crypto/index.js, cli/src/domain/config.js, cli/src/domain/constants.js, cli/src/domain/environment.js, cli/src/domain/printVersion.js, cli/src/domain/project.js, cli/src/domain/project.spec.js, cli/src/domain/tag.js, cli/src/format/guessFormat.js, cli/src/format/index.js, cli/src/format/index.spec.js, cli/src/format/toFlat.js, cli/src/index.js, cli/src/ui/console.js, docs/Usage.md
=> Store encoded credentials in a single environment variable

api/package-lock.json, cli/package-lock.json, test/package-lock.json
=> [RFR] Fix vulnerabilities

api/migrations/20200325133153-add-token-table.js, api/src/domain/permissions.js, api/src/domain/projects/add.js, api/src/queries/knex.js, api/src/queries/projects.js, api/src/queries/tokens.js, api/var/schema.sql, test/Makefile
Related to #130 
- Introduce the new token command management
=> API Token management (1/2)

api/migrations/20200325133153-add-token-table.js, api/package-lock.json, api/package.json, api/serverless.yml, api/src/domain/errors.js, api/src/domain/permissions.js, api/src/domain/projects/add.js, api/src/domain/tokens/add.js, api/src/domain/tokens/generateRandomString.js, api/src/domain/tokens/get.js, api/src/domain/tokens/remove.js, api/src/handlers/tokens.js, api/src/handlers/utils/errors.js, api/src/queries/tokens.js, api/var/schema.sql, cli/package-lock.json, cli/package.json, cli/src/commands/tag.js, cli/src/commands/token.js, cli/src/domain/token.js, cli/src/index.js, cli/src/ui/console.js, test/Makefile, test/specs/commands.js
Fixes #130 
Sorry, I used prettier on this branch too, I recomend reviewing without the whitespaces
- project deploy via a new token (this doesn't require breaking changes)
=> API Token management (2/2)
